import {readFileSync} from 'node:fs';
import {creatorLineColors} from '../src/data/creatorColors';
const svg=readFileSync('src/assets/map.svg','utf8');
const fs:Record<string,number>={};const fw:Record<string,boolean>={};
for(const b of svg.match(/<style[^>]*>([\s\S]*?)<\/style>/g)||[])for(const m of b.matchAll(/\.(st\d+)\s*\{([^}]+)\}/g)){const f=/font-size:\s*([\d.]+)/.exec(m[2]);if(f)fs[m[1]]=+f[1];fw[m[1]]=/font-family:[^;}]*Bold/i.test(m[2]);}
for(const m of svg.matchAll(/<text\b([^>]*)>([\s\S]*?)<\/text>/g)){const txt=m[2].replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim();const c=/class="(st\d+)"/.exec(m[1])?.[1]||'';const t=/matrix\(([^)]+)\)/.exec(m[1]);const n=t?t[1].split(/[\s,]+/).map(Number):[0,0,0,0,0,0];if(/^Call Me Madam$/i.test(txt)||/^Kismet$/i.test(txt)||/^The Pirates/i.test(txt))console.log(`"${txt}" class=${c} fontSize=${fs[c]} bold=${fw[c]} at(${Math.round(n[4])},${Math.round(n[5])})`);}
function sampleD(d:string){const o:{x:number,y:number}[]=[];let cx=0,cy=0,sx=0,sy=0;const tk=d.match(/[a-zA-Z]|-?\d*\.?\d+(?:e[+-]?\d+)?/g)||[];let i=0,c='';const L=(x0:number,y0:number,x1:number,y1:number)=>{const n=Math.max(1,Math.ceil(Math.hypot(x1-x0,y1-y0)/4));for(let s=0;s<=n;s++){const t=s/n;o.push({x:x0+(x1-x0)*t,y:y0+(y1-y0)*t});}};const C=(x0:number,y0:number,a:number,b:number,e:number,f:number,x3:number,y3:number)=>{for(let s=0;s<=14;s++){const t=s/14,it=1-t;o.push({x:it*it*it*x0+3*it*it*t*a+3*it*t*t*e+t*t*t*x3,y:it*it*it*y0+3*it*it*t*b+3*it*t*t*f+t*t*t*y3});}};while(i<tk.length){const t=tk[i];if(/[a-zA-Z]/.test(t)){c=t;i++;continue;}const u=c.toUpperCase();const r=c!==u;const P=()=>{const x=+tk[i++],y=+tk[i++];return r?[cx+x,cy+y]:[x,y];};if(u==='M'){const[x,y]=P();cx=x;cy=y;sx=x;sy=y;o.push({x,y});c=r?'l':'L';}else if(u==='L'||u==='T'){const[x,y]=P();L(cx,cy,x,y);cx=x;cy=y;}else if(u==='H'){const v=+tk[i++];const x=r?cx+v:v;L(cx,cy,x,cy);cx=x;}else if(u==='V'){const v=+tk[i++];const y=r?cy+v:v;L(cx,cy,cx,y);cy=y;}else if(u==='C'){const[a,b]=P();const[e,f]=P();const[x,y]=P();C(cx,cy,a,b,e,f,x,y);cx=x;cy=y;}else if(u==='S'||u==='Q'){i+=2;const[x,y]=P();L(cx,cy,x,y);cx=x;cy=y;}else if(u==='A'){i+=5;const[x,y]=P();L(cx,cy,x,y);cx=x;cy=y;}else if(u==='Z'){L(cx,cy,sx,sy);cx=sx;cy=sy;}else i++;}return o;}
function linePts(hex:string){const cls=new Set<string>();for(const b of svg.match(/<style[^>]*>([\s\S]*?)<\/style>/g)||[])for(const m of b.matchAll(/\.(st\d+)\s*\{([^}]+)\}/g)){if(new RegExp('stroke:'+hex+'\\b','i').test(m[2])){const fm=/(?:^|[;{\s])fill\s*:\s*([^;}]+)/.exec(m[2]);if(!fm||fm[1].trim().toLowerCase()==='none')cls.add(m[1]);}}const pts:{x:number,y:number}[]=[];for(const c of cls){for(const m of svg.matchAll(new RegExp('<path\\b[^>]*\\bclass="'+c+'"[^>]*\\bd="([^"]+)"','g')))pts.push(...sampleD(m[1]));for(const m of svg.matchAll(new RegExp('<line\\b[^>]*\\bclass="'+c+'"[^>]*>','g'))){const tt=m[0];const g=(a:string)=>+(new RegExp('\\b'+a+'="([\\d.\\-]+)"').exec(tt)?.[1]??'NaN');pts.push(...sampleD('M'+g('x1')+','+g('y1')+'L'+g('x2')+','+g('y2')));}}return pts;}
const danHex=String(creatorLineColors['GRACIELA DANIELE']);
console.log('Daniele color',danHex);
const dan=linePts(danHex).filter(q=>q.x>850&&q.x<1350&&q.y>1330&&q.y<1650).sort((a,b)=>a.y-b.y);
console.log('Daniele local pts',dan.length);
for(const q of dan)process.stdout.write(`(${q.x.toFixed(0)},${q.y.toFixed(0)}) `);
console.log();
